# Setup
title:               Zig Brasil
tagline:             'Comunidade Zig Brasil'
description:         'Compartilhando encontros e possíveis projetos realizados no brazil com Zig (linguagem e toolchain).'
url:                 https://zig-brasil.github.io
baseurl:             '/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Matheus Catarino França
  url:               https://kassane.github.io
  email:             matheus-catarino@hotmail.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-redirect-from

# Custom vars
version:             1.1.0
github:
  repo:              https://github.com/zig-brasil/zig-brasil.github.io

prose:
  ignore:
    - /\..*
    - /_config.yml
    - /atom.xml
    - /LICENSE
    - /_layouts
    - /_includes
    - /public
    - /_posts
  metadata:
    "":
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          value: false
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          value: false